directories:
  output: application
  buildResources: build
appId: com.quanbian.timer
productName: 全辩计时器
files:
  - filter:
      - dist/**/*
      - main.js
extraMetadata:
  main: main.js
mac:
  category: public.app-category.utilities
win:
  target: nsis
linux:
  target: deb
electronVersion: 35.1.2
